[project]
name = "assignment1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "blessed>=1.22.0",
    "pysqlite3>=0.5.4",
    "pytest>=8.4.2",
]
